export const cabs = [
    {
        id: '1',
        companyName: 'Uber',
        carModel: 'Toyota Camry',
        passengers: 4,
        rating: 4.5,
        costPerHour: 25,
        imageUrl: 'https://example.com/uber_camry.jpg',
    },
    {
        id: '2',
        companyName: 'Lyft',
        carModel: 'Honda Civic',
        passengers: 4,
        rating: 4.2,
        costPerHour: 22,
        imageUrl: 'https://example.com/lyft_civic.jpg',
    },
    {
        id: '3',
        companyName: 'Yellow Cab',
        carModel: 'Ford Fusion',
        passengers: 4,
        rating: 3.8,
        costPerHour: 20,
        imageUrl: 'https://example.com/yellow_fusion.jpg',
    },
    {
        id: '4',
        companyName: 'Green Taxi',
        carModel: 'Toyota Prius',
        passengers: 4,
        rating: 4.0,
        costPerHour: 23,
        imageUrl: 'https://example.com/green_prius.jpg',
    },
    {
        id: '5',
        companyName: 'Black Car',
        carModel: 'Mercedes-Benz E-Class',
        passengers: 4,
        rating: 4.7,
        costPerHour: 35,
        imageUrl: 'https://example.com/black_mercedes.jpg',
    },
    {
        id: '6',
        companyName: 'City Rides',
        carModel: 'Chevrolet Malibu',
        passengers: 4,
        rating: 3.9,
        costPerHour: 21,
        imageUrl: 'https://example.com/city_malibu.jpg',
    },
    {
        id: '7',
        companyName: 'Luxury Limo',
        carModel: 'BMW 7 Series',
        passengers: 4,
        rating: 4.8,
        costPerHour: 50,
        imageUrl: 'https://example.com/luxury_bmw.jpg',
    },
    {
        id: '8',
        companyName: 'EcoCab',
        carModel: 'Nissan Leaf',
        passengers: 4,
        rating: 4.3,
        costPerHour: 24,
        imageUrl: 'https://example.com/eco_leaf.jpg',
    },
    {
        id: '9',
        companyName: 'Fast Taxi',
        carModel: 'Ford Escape',
        passengers: 5,
        rating: 4.1,
        costPerHour: 26,
        imageUrl: 'https://example.com/fast_escape.jpg',
    },
    {
        id: '10',
        companyName: 'Family Van',
        carModel: 'Chrysler Pacifica',
        passengers: 7,
        rating: 4.4,
        costPerHour: 30,
        imageUrl: 'https://example.com/family_pacifica.jpg',
    },
    {
        id: '11',
        companyName: 'Airport Express',
        carModel: 'Toyota Sienna',
        passengers: 6,
        rating: 4.2,
        costPerHour: 28,
        imageUrl: 'https://example.com/airport_sienna.jpg',
    },
    {
        id: '12',
        companyName: 'Luxury SUV',
        carModel: 'Cadillac Escalade',
        passengers: 6,
        rating: 4.6,
        costPerHour: 45,
        imageUrl: 'https://example.com/luxury_escalade.jpg',
    },
];

export const bookedCabs = [
    {
        id: '1',
        companyName: 'Uber',
        carModel: 'Toyota Camry',
        bookingTime: '2023-08-02T10:30:00Z',
        status: 'Active',
    },
    {
        id: '5',
        companyName: 'Black Car',
        carModel: 'Mercedes-Benz E-Class',
        bookingTime: '2023-08-01T14:15:00Z',
        status: 'Completed',
    },
];